export const SET_SELECTED_LOCATIONS = 'SET_SELECTED_LOCATIONS';
export const SET_LOCATIONS = 'SET_LOCATIONS';
export const START_LOADING = 'START_LOADING';
export const STOP_LOADING = 'STOP_LOADING';
export const SET_WEATHER_INFOS = 'SET_WEATHER_INFOS';
export const SET_UNITS = 'SET_UNITS';