export const SET_SELECTED_LOCATION = 'SET_SELECTED_LOCATION';
export const SET_LOCATIONS = 'SET_LOCATIONS';
export const START_LOADING = 'START_LOADING';
export const STOP_LOADING = 'STOP_LOADING';
export const SET_WEATHER_INFO = 'SET_WEATHER_INFO';
export const SET_UNITS = 'SET_UNITS';